services:
  - type: web
    name: geopoliticsweb
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    instanceType: free
    envVars:
      - key: FLASK_ENV
        value: production